apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: teamshift-ingress
  namespace: loic
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: teamshift.loic.k8s.crossknowledge.com.br
    http:
      paths:
      - path: /
        backend:
          serviceName: teamshift
          servicePort: 80
